In [1]:
import pandas as pd
df = pd.read_excel('C:\\Users\\SERVER\\Downloads\\customer_reviews_dataset.xlsx')

In [2]:
df

,customer_id,age,income,years_experience,city,device,product_category,rating,purchased
0,1,23,25000,1,Nairobi,Mobile,Electronics,4,Yes
1,2,45,120000,20,Mombasa,Laptop,Home,5,Yes
2,3,34,54000,8,Kisumu,Tablet,Electronics,3,No
3,4,29,48000,5,Nairobi,Mobile,Fashion,4,Yes
4,5,52,220000,25,Nakuru,Laptop,Home,5,Yes
5,6,41,67000,12,Eldoret,Mobile,Electronics,2,No
6,7,37,72000,10,Nairobi,Tablet,Fashion,4,Yes
7,8,26,31000,3,Mombasa,Mobile,Electronics,3,No
8,9,48,98000,22,Kisumu,Laptop,Home,5,Yes
9,10,31,45000,6,Nakuru,Mobile,Fashion,4,Yes
10,11,27,38000,4,Eldoret,Tablet,Electronics,3,No
11,12,56,300000,30,Nairobi,Laptop,Home,5,Yes
12,13,33,52000,7,Mombasa,Mobile,Electronics,2,No
13,14,22,21000,1,Kisumu,Mobile,Fashion,4,Yes
14,15,39,76000,14,Nakuru,Tablet,Electronics,3,No
15,16,44,89000,18,Eldoret,Laptop,Home,5,Yes
16,17,28,42000,4,Nairobi,Mobile,Fashion,4,Yes
17,18,36,68000,11,Mombasa,Tablet,Electronics,3,No
18,19,50,150000,24,Kisumu,Laptop,Home,5,Yes
19,20,24,27000,2,Nakuru,Mobile,Fashion,4,Yes

In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
x = df.drop(['purchased', 'customer_id'], axis=1)
y = df['purchased']

In [6]:
df.columns

Index(['customer_id', 'age', 'income', 'years_experience', 'city', 'device',
       'product_category', 'rating', 'purchased'],
      dtype='str')

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
cat_cols = ['city', 'device','product_category']
num_cols = ['age', 'income', 'years_experience', 'rating']

In [11]:
preprocessor = ColumnTransformer(
    transformers = [
        ('cat', OneHotEncoder(), cat_cols),
        ('num', StandardScaler(), num_cols)
    ]
)

In [12]:
from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ('preprocess', preprocessor),
    ('model', DecisionTreeClassifier())
])

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)
pipeline.fit(X_train, Y_train)
pipeline.predict(X_test)

array(['No', 'No', 'Yes', 'Yes'], dtype=object)

In [16]:
pipeline.score(X_test, Y_test)

1.0

In [20]:
Y_test

5      No
2      No
18    Yes
4     Yes
Name: purchased, dtype: str

In [23]:
X_test

    age  income  years_experience     city  device product_category  rating
5    41   67000                12  Eldoret  Mobile      Electronics       2
2    34   54000                 8   Kisumu  Tablet      Electronics       3
18   50  150000                24   Kisumu  Laptop             Home       5
4    52  220000                25   Nakuru  Laptop             Home       5